name: pre-commit

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit:
    if: github.repository == 'Inf2-SEPP-CW-2026/CourseWork'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
